name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v3
        with:
          include-v-in-tag: true
          command: manifest
          default-branch: master
          token: ${{ secrets.GITHUB_TOKEN }}